### ISSUE TITLE
Zipkin bad json encoding

### ISSUE THREAD

**Issue by n0tl3ss** [micronaut-projects/micronaut-tracing#316]
### Expected Behavior

Spans to be valid json array

### Actual Behaviour

Spans array is not properly json encoded

```
POST /api/v2/spans HTTP/1.1
host: localhost:9411
Connection: close
content-type: application/json
Content-Length: 284

][{"traceId":"2f1dd400d27b399a","id":"2f1dd400d27b399a","kind":"SERVER","name":"get","timestamp":1686134923454707,"duration":9948,"localEndpoint":{"serviceName":"tracing-test","ipv4":"192.168.205.1"},"tags":{"error":"404","http.method":"GET","http.path":"/","http.status_code":"404"}}
```
### Steps To Reproduce

1. Create application that will use zipking tracing (opentracing)
2. Visit page that doesn't exists (returns 404)
3. Observe zipkin client request body

### Version

3.9.3

**Comment by graemerocher** [comment]
not sure, but a fix needs to be applied to 3.x as well as it impacts teams using 3.x

**Comment by yawkat** [comment]
ok

**Comment by yawkat** [comment]
how exactly do i reproduce this? i tried a simple test project and the json was valid: 
![image](https://github.com/micronaut-projects/micronaut-tracing/assets/2395297/ef102db4-80f7-4a93-b302-4b8a38542e54)

**Comment by graemerocher** [comment]
@n0tl3ss can you help @yawkat reproduce

**Comment by yawkat** [comment]
can you share your example project?

**Comment by n0tl3ss** [comment]
[tracing-demo-json.zip](https://github.com/micronaut-projects/micronaut-tracing/files/11679341/tracing-demo-json.zip)

It is baisc project with zipkin from launcher, just change configuration to:
```
micronaut:
  application:
    name: tracingDemoJson
netty:
  default:
    allocator:
      max-order: 3
tracing:
  zipkin:
    enabled: true
    http:
      url: <url-from-requestbin>
    sampler:
      probability: 1
```
